import type { Metadata } from "next";
import "./globals.css";
import { Exo } from "next/font/google";

const exo = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Space App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={exo.className}>
      <head>
        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Space App" />
        <meta
          property="og:description"
          content="Generated by create next app"
        />
        <meta property="og:image" content="/og-image.png" />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Space App" />
        <meta
          name="twitter:description"
          content="Generated by create next app"
        />
        <meta name="twitter:image" content="/twitter-image.png" />
        <title>Space App</title>
      </head>
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
